### ISSUE TITLE
Add me as a contributor?

### ISSUE THREAD

**Issue by rvosa** [cjfields/bioperl6#6]
Hi Chris,

there might come a moment in my copious amounts of spare time where I'd like to try out perl6 implementations of phylogenetic trees, nodes and taxa. Might as well do this as part of bioperl6, so if you trust me enough not to make too much of a mess, may I have push access?

Thanks,

Rutger

**Comment by cjfields** [comment]
Why certainly :).  Will add you to the team

**Comment by cjfields** [comment]
You should have push now.  I may move this over to the main bioperl org at some point but will transfer everyone there if that happens.

**Comment by rvosa** [comment]
Thanks, pushing works.
